blank_issues_enabled: false
contact_links:
  - name:  Обсуждение архитектуры
    url: https://github.com/clevergg/Swift/discussions
    about: Для архитектурных вопросов и обсуждений используйте Discussions
